# nile.toml file generated for nifedocgitac on 2023-12-18T11:50:46+05:30

app = "nifedocgitac"
id = "5bba275301a7545dfc9eaf07af12e7bb273af00cb4fecbe96bc58c6d13ff4e93d9aca202902b614f1c73b9806076f8bc"

[build]
  builtin = "static react"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = 80
  http_checks = []
  internal_port = 3000
  protocol = "tcp"
  routing_policy = "Geolocation"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "1"
    memory = "256"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "0.5"
    memory = "128"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
